fix typos in test 11

diff --git a/tests/unit/parser_test11/Makefile b/tests/unit/parser_test11/Makefile
--- a/tests/unit/parser_test11/Makefile
+++ b/tests/unit/parser_test11/Makefile
@@ -7,9 +7,9 @@ build:
 run: build
 	@echo "[info] performing test parser 10"
 	
-	./$(NAME) < ./input.txt > ./output.txt 2>./debug_output.txt || (echo -e "[info] test parser 10 - missing ID decl [RET_CODE] \e[31mFAIL\e[0m" && exit 1)
-	diff ./expected_debug.txt ./debug_output.txt || (echo -e "[info] test parser 10 - missing ID decl [RULE_PRINT] \e[31mFAIL\e[0m" && exit 1)
-	diff ./expected.txt ./output.txt || (echo -e "[info] test parser 10 - missing ID decl [INSTR] \e[31mFAIL\e[0m" && exit 1)
+	./$(NAME) < ./input.txt > ./output.txt 2>./debug_output.txt || (echo -e "[info] test parser 11 - bad syntax missing cond clause [RET_CODE] \e[31mFAIL\e[0m" && exit 1)
+	diff ./expected_debug.txt ./debug_output.txt || (echo -e "[info] test parser 11 - bad syntax missing cond clause [RULE_PRINT] \e[31mFAIL\e[0m" && exit 1)
+	diff ./expected.txt ./output.txt || (echo -e "[info] test parser 11 - bad syntax missing cond clause [INSTR] \e[31mFAIL\e[0m" && exit 1)
 	echo -e "[info] test parser 10 - function calls \e[32mPASS\e[0m"
 
 artifacts:
