edit: parser test 6: redirecting rule print and instructions

diff --git a/tests/unit/parser_test06/Makefile b/tests/unit/parser_test06/Makefile
--- a/tests/unit/parser_test06/Makefile
+++ b/tests/unit/parser_test06/Makefile
@@ -7,11 +7,13 @@ build:
 run: build
 	@echo "[info] performing test parser 6"
 	
-	./$(NAME) < ./input.txt > ./output.txt 2>&1
-	diff ./expected.txt ./output.txt || (echo -e "[info] test parser 06 - function calls \e[31mFAIL\e[0m" && exit 1)
+	./$(NAME) < ./input.txt > ./output.txt 2>./debug_output.txt
+	diff ./expected_debug.txt ./debug_output.txt || (echo -e "[info] test parser 06 - function calls [RULE_PRINT] \e[31mFAIL\e[0m" && exit 1)
+	diff ./expected.txt ./output.txt || (echo -e "[info] test parser 06 - function calls [INSTR] \e[31mFAIL\e[0m" && exit 1)
 	echo -e "[info] test parser 06 - function calls \e[32mPASS\e[0m"
 
 artifacts:
 	@echo "[info] creating artifacts for parser 6"
 	@echo "----------------------------------------"
-	cp output.txt ../test_artifacts/units_test_parser6.txt	
+	cp output.txt ../test_artifacts/units_test_parser6.txt		
+	cp debug_output.txt ../test_artifacts/units_test_parser6_rule_print.txt
