fixing some typos in tests again

diff --git a/tests/unit/parser_test12/Makefile b/tests/unit/parser_test12/Makefile
--- a/tests/unit/parser_test12/Makefile
+++ b/tests/unit/parser_test12/Makefile
@@ -7,10 +7,10 @@ build:
 run: build
 	@echo "[info] performing test parser 12"
 	
-	./$(NAME) < ./input.txt > ./output.txt 2>./debug_output.txt || (echo -e "[info] test parser 012 - func_decl with body ,func calls and eols [RET_CODE] \e[31mFAIL\e[0m" && exit 1)
-	diff ./expected_debug.txt ./debug_output.txt || (echo -e "[info] test parser 012 - func_decl with body ,func calls and eols [RULE_PRINT] \e[31mFAIL\e[0m" && exit 1)
-	diff ./expected.txt ./output.txt || (echo -e "[info] test parser 012 - func_decl with body ,func calls and eols [INSTR]\e[31mFAIL\e[0m" && exit 1)
-	echo -e "[info] test parser 01 - empty input file \e[32mPASS\e[0m"
+	./$(NAME) < ./input.txt > ./output.txt 2>./debug_output.txt || (echo -e "[info] test parser 12 - func_decl with body ,func calls and eols [RET_CODE] \e[31mFAIL\e[0m" && exit 1)
+	diff ./expected_debug.txt ./debug_output.txt || (echo -e "[info] test parser 12 - func_decl with body ,func calls and eols [RULE_PRINT] \e[31mFAIL\e[0m" && exit 1)
+	diff ./expected.txt ./output.txt || (echo -e "[info] test parser 12 - func_decl with body ,func calls and eols [INSTR]\e[31mFAIL\e[0m" && exit 1)
+	echo -e "[info] test parser 12 - func_decl with body ,func calls and eols \e[32mPASS\e[0m"
 
 
 artifacts:
