edit code_generator test 1

diff --git a/tests/unit/code_generator_test1/Makefile b/tests/unit/code_generator_test1/Makefile
--- a/tests/unit/code_generator_test1/Makefile
+++ b/tests/unit/code_generator_test1/Makefile
@@ -8,9 +8,11 @@ build:
 run: build
 	@echo "[info] performing test code generator 1"
 	./$(NAME) > ./output.txt 2>&1
-	diff ./expected.txt ./output.txt || (echo -e "[info] test code generator 1 \e[31mFAIL\e[0m" && exit 1)
+	./ic23int ./output.txt < input.txt > ./runOutput.txt 2>&1
+	diff ./expected.txt ./runOutput.txt || (echo -e "[info] test code generator 1 \e[31mFAIL\e[0m" && exit 1)
 	echo -e "[info] test code generator 1 \e[32mPASS\e[0m"
 
 artifacts:
 	@echo "[info] creating artifacts for code generator 1"
-	cp output.txt ../test_artifacts/units_test_code_generator1.txt
+	cp output.txt ../test_artifacts/units_test_code_generator1_asm.txt
+	cp runOutput.txt ../test_artifacts/units_test_code_generator1_out.txt
