edit: parser test 3: redirecting rule print and instructions

diff --git a/tests/unit/parser_test03/Makefile b/tests/unit/parser_test03/Makefile
--- a/tests/unit/parser_test03/Makefile
+++ b/tests/unit/parser_test03/Makefile
@@ -7,12 +7,14 @@ build:
 run: build
 	@echo "[info] performing test parser 3"
 	
-	./$(NAME) < ./input.txt > ./output.txt 2>&1
-	diff ./expected.txt ./output.txt || (echo -e "[info] test parser 03 - let declaration \e[31mFAIL\e[0m" && exit 1)
+	./$(NAME) < ./input.txt > ./output.txt 2>./debug_output.txt
+	diff ./expected_debug.txt ./debug_output.txt || (echo -e "[info] test parser 03 - let declaration [RULE_PRINT] \e[31mFAIL\e[0m" && exit 1)
+	diff ./expected.txt ./output.txt || (echo -e "[info] test parser 03 - let declaration [INSTR] \e[31mFAIL\e[0m" && exit 1)
 	echo -e "[info] test parser 03 - let declaration \e[32mPASS\e[0m"
 
 
 artifacts:
 	@echo "[info] creating artifacts for parser 3"
 	@echo "----------------------------------------"
-	cp output.txt ../test_artifacts/units_test_parser3.txt	
+	cp output.txt ../test_artifacts/units_test_parser3.txt		
+	cp debug_output.txt ../test_artifacts/units_test_parser3_rule_print.txt	
