fixed return code check in Makefile && changed exp ret code in program1-5

diff --git a/tests/unit/parser/Makefile b/tests/unit/parser/Makefile
--- a/tests/unit/parser/Makefile
+++ b/tests/unit/parser/Makefile
@@ -16,19 +16,21 @@ build: $(OBJ)
 
 
 run: build
+	ERROR=0
 	@$(foreach dir,$(DIRECTORIES), \
 		if [ -d "$(dir)" -a "$$(echo -n "$(dir)" | tail -c 1)" != "-" ]; then \
 			FILENAME=$$(basename $(dir)); \
 			./$(NAME) < "$(dir)/$${FILENAME}".swift > ./output.txt 2>debug_output.txt; \
-			{ [[ "$$?" -eq "$$(cat "$(dir)/$${FILENAME}".ret)" ]]; } || \
-				{ echo -e "[info] test parser $${FILENAME} [RET_CODE] \e[31mFAIL\e[0m" ;}; \
-			echo -e "ret:"$$?" exp:"$$(cat "$(dir)/$${FILENAME}".ret)""; \
+			RET_CODE=$$?; \
+			echo -e "ret:"$${RET_CODE}" exp:"$$(cat "$(dir)/$${FILENAME}".ret)""; \
+			{ [[ "$${RET_CODE}" -eq "$$(cat "$(dir)/$${FILENAME}".ret)" ]]; } || \
+				{ echo -e "[info] test parser $${FILENAME} [RET_CODE] \e[31mFAIL\e[0m" && ERROR=1;}; \
 			cp output.txt ../test_artifacts/units_test_parser_"$${FILENAME}".txt; \
 			cp debug_output.txt ../test_artifacts/units_test_parser_"$${FILENAME}"_debug.txt; \
 			{ diff "./$(dir)$${FILENAME}_debug.expected" ./debug_output.txt; } || \
-				{ echo -e "[info] test parser $${FILENAME} [RULE] \e[31mFAIL\e[0m" ; }; \
+				{ echo -e "[info] test parser $${FILENAME} [RULE] \e[31mFAIL\e[0m" && ERROR=1; }; \
 			{ diff "$(dir)/$${FILENAME}".expected ./output.txt; } || \
-				{ echo -e "[info] test parser $${FILENAME} [INSTR] \e[31mFAIL\e[0m" ; }; \
+				{ echo -e "[info] test parser $${FILENAME} [INSTR] \e[31mFAIL\e[0m" && ERROR=1; }; \
 			echo -e "[info] test parser $${FILENAME} \e[32mOK\e[0m"; \
 			$(VALGRIND) ./$(NAME) < "$(dir)/$${FILENAME}.swift" > ./valgrind_output.txt 2>&1 || \
 				{ echo -e "[info] valgrind check $${FILENAME} \e[32mOK\e[0m" || \
@@ -37,6 +39,7 @@ run: build
 			echo -e "----------------------------------------"; \
 		fi; \
 	)
+	{ [[ "$${ERROR}" -eq "1" ]]; } || {exit 1;}
 
 artifacts:
 
