edit tests exp outputs

diff --git a/tests/unit/parser/Makefile b/tests/unit/parser/Makefile
--- a/tests/unit/parser/Makefile
+++ b/tests/unit/parser/Makefile
@@ -23,14 +23,14 @@ run: build
 			RET_CODE=$$?; \
 			echo -e "ret:"$${RET_CODE}" exp:"$$(cat "$(dir)/$${FILENAME}".ret)""; \
 			{ [[ "$${RET_CODE}" -eq "$$(cat "$(dir)/$${FILENAME}".ret)" ]]; } || \
-				{ echo -e "[info] test parser $${FILENAME} [RET_CODE] \e[31mFAIL\e[0m" && ERROR=1;}; \
+				{ echo -e "[info] test parser $${FILENAME} [RET_CODE] \e[31mFAIL\e[0m" && exit 1;}; \
 			mkdir -p ../test_artifacts/"parser_$${FILENAME}"/ ; \
 			cp output.txt ../test_artifacts/"parser_$${FILENAME}"/"$${FILENAME}".txt; \
 			cp debug_output.txt ../test_artifacts/"parser_$${FILENAME}"/"$${FILENAME}"_debug.txt; \
 			{ diff "./$(dir)$${FILENAME}_debug.expected" ./debug_output.txt; } || \
-				{ echo -e "[info] test parser $${FILENAME} [RULE] \e[31mFAIL\e[0m" && ERROR=1; }; \
+				{ echo -e "[info] test parser $${FILENAME} [RULE] \e[31mFAIL\e[0m" && exit 1; }; \
 			{ diff "$(dir)/$${FILENAME}".expected ./output.txt; } || \
-				{ echo -e "[info] test parser $${FILENAME} [INSTR] \e[31mFAIL\e[0m" && ERROR=1; }; \
+				{ echo -e "[info] test parser $${FILENAME} [INSTR] \e[31mFAIL\e[0m" && exit 1; }; \
 			echo -e "[info] test parser $${FILENAME} \e[32mOK\e[0m"; \
 			$(VALGRIND) ./$(NAME) < "$(dir)/$${FILENAME}.swift" > ./valgrind_output.txt 2>&1 || \
 				{ echo -e "[info] valgrind check $${FILENAME} \e[32mOK\e[0m" || \
@@ -38,8 +38,7 @@ run: build
 			cp valgrind_output.txt ../test_artifacts/"parser_$${FILENAME}"/"$${FILENAME}"_valgrind.txt; \
 			echo -e "----------------------------------------"; \
 		fi; \
-    ) \
-    [ $(ERROR) -eq 1 ] || exit 1;
+	)
 	
 
 artifacts:
